---
#
# Installing Filebeat
#

# Install Filebeat 

- name: Install Filebeat with apt
  yum:
    name: filebeat
    state: latest 

 # Starting Filebeat

- name: Starting Filebeat
  systemd:
      name: filebeat
      state: started
