---
#
# Installing Kibana
#

# Install Kibana 

- name: Install Kibana with yum
  yum:
      name: kibana
      state: latest

      # Configurations

- name: Updating the config file to allow outside access
  lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'server.host:'
      line: 'server.host: 0.0.0.0'

- name: Defining server port
  lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'server.port:'
      line: 'server.port: 5601'

- name: Defining Elasticsearch URL
  lineinfile:
      destfile: /etc/kibana/kibana.yml
      regexp: 'elasticsearch.url:'
      line: 'elasticsearch.url: "http://localhost:9200"'

      # Starting Kibana

- name: Starting Kibana
  systemd:
      name: kibana
      state: started
