---
#
# Installing Metricbeat
#

# Install Metricbeat 

- name: Install Metricbeat with apt
  yum:
      name: metricbeat
      state: latest 

      # Starting Metricbeat

- name: Starting Metricbeat
  systemd:
      name: metricbeat
      state: started
