---
#
# Installing Elasticsearch
#

# Add Elasticsearch apt key

- name: Add Elasticsearch apt key
  shell: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

  # Add the Elasticsearch apt repo. For versions 6 of the stack - use '6.x-prerelease':

- name: Adding Elasticsearch repo
  copy:
      src: elasticsearch.repo
      dest:  /etc/yum.repos.d/elasticsearch.repo

      # Installing Elasticsearch

- name: Install Elasticsearch
  yum:
      name: elasticsearch
      state: latest

      # Update Elasticsearch config file to allow access (to secure Elasticsearch, bind to 'localhost'). 

- name: Updating the config file to allow outside access
  lineinfile:
      destfile: /etc/elasticsearch/elasticsearch.yml
      regexp: 'network.host:'
      line: 'network.host: 0.0.0.0'

      # Update Elasticsearch port in config file 

- name: Updating the port in config file 
  lineinfile:
      destfile: /etc/elasticsearch/elasticsearch.yml
      regexp: 'http.port:'
      line: 'http.port: 9200'

      #Start Elasticsearch
- name: Starting Elasticsearch
  systemd:
      name: elasticsearch
      state: started

